<?php

namespace Liquidaciones\HaberesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HAConceptosValorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HAConceptosValorRepository extends EntityRepository
{
}
