<?php

namespace Liquidaciones\HaberesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HADependenciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HADependenciasRepository extends EntityRepository
{
}
