<?php

namespace Liquidaciones\ReferenciasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DependenciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependenciasRepository extends EntityRepository
{
}
