<?php

namespace Liquidaciones\ReferenciasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Imppresupff11Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Imppresupff11Repository extends EntityRepository
{
}
