<?php

namespace Liquidaciones\ReferenciasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImputacionDependenciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImputacionDependenciasRepository extends EntityRepository
{
}
