services:
    security.authentication.factory.intranet:
        class:  Liquidaciones\IntranetBundle\DependencyInjection\Security\Factory\IntranetFactory
        tags:
                - { name: security.listener.factory }
