imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
            
framework:
    secret:          "%secret%"
    translator:      { fallback: "%locale%", enabled: true }
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

#web_profiler:
#    toolbar: %debug_toolbar%
#    intercept_redirects: %debug_redirects%
    
services:
    my.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit 
        tags:
            - { name: doctrine.event_listener, event: postConnect, connect: default}

monolog:
     handlers:
         main:
             type: "null"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        host_server:  %host_server%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:     ms_haberes_web
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  ISO-8859-1
              # if using pdo_sqlite as your database driver, add the path in parameters.yml
              # e.g. database_path: "%kernel.root_dir%/data/data.db3"
              # path:     "%database_path%"
            referencias:
                driver:   "%database_driver_referencias%"
                host:     "%database_host_referencias%"
                port:     "%database_port_referencias%"
                dbname:   "%database_name_referencias%"
                user:     "%database_user_referencias%"
                password: "%database_password_referencias%"
                charset:  UTF8
            intranet:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name_intranet%
                user:     %database_user_intranet%
                password: %database_password_intranet%
                charset:  WE8ISO8859P1
            ms_haberes_web:
                driver:   %database_driver_ms_web%
                host:     %database_host_ms_web%
                port:     %database_port_ms_web%
                dbname:   %database_name_ms_web%
                user:     %database_user_ms_web%
                password: %database_password_ms_web%
                charset:  ISO-8859-1
            odbc_haberes:
                driver:   %database_driver_odbc%
                host:     %database_host_odbc%
                port:     %database_port_odbc%
                dbname:   %database_name_odbc%
                user:     %database_user_odbc%
                password: %database_password_odbc%
                charset:  ISO-8859-1
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:   ms_haberes_web
        entity_managers:
            default:
                connection:       default
                mappings:
                    LiquidacionesReferenciasBundle: ~
            referencias:
                connection:       referencias
                mappings:
                    LiquidacionesReferenciasBundle: ~
            intranet:
                connection:       intranet
                mappings:
                    LiquidacionesIntranetBundle: ~
            ms_haberes_web:  
                connection:       ms_haberes_web
                mappings:
                    LiquidacionesCuposAnualesBundle: ~
                    LiquidacionesHaberesBundle: ~
                    LiquidacionesParteNovedadesBundle: ~
                dql:
                    string_functions:
                        reemplazar: Liquidaciones\HaberesBundle\DQL\reemplazar    
            odbc_haberes:
                connection:       odbc_haberes
                mappings:

    
    
