<?php

namespace Liquidaciones\IntranetBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * UsuariosIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosIRepository extends EntityRepository implements UserProviderInterface
{

    public function loadUserByUsername($username) {        
        $statement = 'SELECT a.nombreusuario, a.id_sesion FROM seguridad.v_usuarioprofe a WHERE a.nombreusuario = :usr';
        
        $stmt = $this->_em
                ->getConnection()
                ->prepare($statement);
        $stmt->bindValue(':usr', $username);
        
        $stmt->execute();
        
        $q = $stmt->fetch();
        
        $user = new UsuariosI();
        $user->setNombreusuario($q['NOMBREUSUARIO']);
        $user->setIdSession($q['ID_SESION']);
        
        if (isset($_SESSION['SessionInitiated']) && $_SESSION['SessionInitiated']) {
            $user->CodSistema = $_SESSION['CODSISTEMA'];
            $user->DescEstablecimiento = $_SESSION['DescEstablecimiento'];
            $user->DescripcionPerfil = $_SESSION['DESCRIPCIONPERFIL'];
            $user->Id = $_SESSION['Id'];
            $user->IdEstablLargo = $_SESSION['IdEstablLargo'];
            $user->IdEstablecimiento = $_SESSION['IdEstablecimiento'];
            $user->IdPersona = $_SESSION['idPersona'];
            $user->IdUsuario = $_SESSION['idUsuario'];
            $user->NroUsuario = $_SESSION['NroUsuario'];
            $user->PerfilId = "ROLE_" . $_SESSION['PERFILID'];
	    $user->multidep_multi = $_SESSION['MULTIDEP_MULTI'];
            $user->multidep_roles = $_SESSION['MULTIDEP_ROLES'];
            if ($user->multidep_multi)
            {
                $user->multidep_actual = $_SESSION['MULTIDEP_ACTUAL'];
                $user->multidep_actual_descripcion = $_SESSION['MULTIDEP_ACTUAL_DESC'];
                $user->multidep_actual_codigo = $_SESSION['MULTIDEP_ACTUAL_CODIGO'];
                $user->multidep_actual_estable_id = $_SESSION['MULTIDEP_ACTUAL_ESTABLE_ID'];
            }
        }

        return $user;
    }

    public function refreshUser(\Symfony\Component\Security\Core\User\UserInterface $user) {
        $class = get_class($user);
        if (!$this->supportsClass($class)) {
            throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', $class));
        }

        return $this->loadUserByUsername($user->getUsername());
    }

    public function supportsClass($class) {
        return $this->getEntityName() === $class 
                || is_subclass_of($class, $this->getEntityName());
    }
}
