<?php

namespace Liquidaciones\CuposAnualesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuposAnualesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuposAnualesRepository extends EntityRepository
{
    public function findAllSaldo($refcupo)
    {
        return $this->getEntityManager("ms_haberes_web")
            ->createQuery('SELECT c.monto FROM LiquidacionesCuposAnualesBundle:CuposAnuales ca '
                        . ' INNER JOIN LiquidacionesCuposAnualesBundle:Cupos c'
                        . ' WITH ca.id = c.cuposanuales.id '
                        . ' WHERE ca.id = 1')
            ->getResult();
    }
}
