<?php

namespace Liquidaciones\CuposAnualesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CuposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuposRepository extends EntityRepository
{
}
