<?php

namespace Liquidaciones\CuposAnualesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LiquidacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiquidacionesRepository extends EntityRepository
{
}
