<?php

namespace Liquidaciones\CuposAnualesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValidacionModulosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValidacionModulosRepository extends EntityRepository
{
}
